### ISSUE TITLE
Support additional resize methods

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/axon#181]
#72 added resizing of inputs via upsampling or downsampling. Currently, only nearest neighbor resizing is supported. We should also support the following:

- [x] nearest
- [x] linear (linear, bilinear, trilinear)
- [x] cubic (cubic, bicubic, tricubic)

This is pretty consistent with what PyTorch / ONNX / TensorFlow support AFAIK

**Comment by floatn** [comment]
@seanmor5 
I have catmul-rom spline with natural boundary conditions version of cubic interpolation ready. Here're some [comparisons](https://postimg.cc/gallery/5vkTZYw). First three are for `corners_align` version, for different second derivative boundary values. The third one is for `no_align`, which is the worst case since linear extrapolation contributes to error greatly. WDYT?

**Comment by seanmor5** [comment]
@floatn For now let's go with the `corners_align` version. Maybe we can add an option so it is configurable though? Either way please open a PR and your amazing contributions!
