### ISSUE TITLE
Add Axon.deserialize_params / Axon.serialize_params

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/axon#205]
We cannot serialize the result of training directly because it is Axon state (a custom struct), so we need to provide functions for wrapping/unwrapping it.

However, we have an issue in that if we wrap the `Nx.serialize/deserialize` functionality, the current Nx.serialize/deserialize does not allow us to attach any additional metadata to the serialized values, and we likely want to add at least an internal Axon version too.

One option is to allow a `:tag` to be given to `Nx.serialize`, which defaults to `:nx`. On deserialize, we return `{tag, value}`, which by default is `{:nx, container}`. This way we can make the `tag` be a custom map in Axon case, and on deserialization we could compare versions whatever else we want.

We could also serialize models but that's even more complicated.

**Comment by seanmor5** [comment]
Given that this is directly related to Axon Loops, my proposal is to name this something like: `Axon.Loop.checkpoint` or `Axon.Loop.serialize_checkpoint` / `Axon.Loop.deserialize_checkpoint`. It will serialize and deserialize enough information about the loop state to begin training from the checkpoint after loading. It's pretty common to provide full last epoch training checkpoints, so that's what I'm thinking the purpose of this function will be.
