### ISSUE TITLE
Add debug option on Loop.trainer

### ISSUE THREAD

**Issue by fantypants** [elixir-nx/axon#311]
Hello, 

Is there any plans to enable a debug/trace option on the Axon.Loop.trainer? this would be essentially the same as live view's debug on the socket. 

one handy case would be as follows:
You build a model, and initiate the Loop trainer, your loop seems to be not doing much, even with metrics and  handle being set. You would be able to enable the debug trace and see whats happening to the process.

**Comment by seanmor5** [comment]
@fantypants I think this is a great idea! A lot of the pieces are already there---we already support a debug mode in the forward pass of the model so it wouldn't be too difficult to add a debug mode to Loop.

If you want to add a PR for it let me know and I can walk you through the next steps. Otherwise I will get to it at some point

**Comment by fantypants** [comment]
> 

@seanmor5 I would definitely be interested; where do we go from here? =)
