### ISSUE TITLE
Breaking change in Axon.Loop.evaluator 

### ISSUE THREAD

**Issue by dfrt82** [elixir-nx/axon#448]
With commit 7200d91332a45336791a24dda73ba7ea168abf5a the Axon.Loop.evaluator function changed it's arity from /2 to /1, now taking only the model as parameter while formerly taking `model` and `model_state`.

This is problematic as it breaks numerous samples provided on the web, e.g. https://dockyard.com/blog/2022/04/07/catching-fraud-with-elixir-and-axon.

Also the documentation still mentions `model_state` ("Creates a supervised evaluator from a model and model state.") which is obfuscating as it cannot be found within the implementation.

Updating the docs and maybe provide a workaround within this issue for fellow readers would suffice I think. As a beginner I was able to update all the code of the above tutorial to current versions of Nx/Axon/Explorer but not this very function.

Current definition can be found here:
https://github.com/elixir-nx/axon/blob/7200d91332a45336791a24dda73ba7ea168abf5a/lib/axon/loop.ex#L607

**Comment by seanmor5** [comment]
Hi @dfrt82 thanks for pointing this out! Just for some context for you, this had to be done out of necessity, because previously Axon built a closure around the model state, which would result in excessive recompilations when using evaluators in validation loops and in other places. Overall it was pretty bad for performance.

I understand the confusion as many of my Axon posts are from pre-0.1 and the stability of the API has been iffy until recently. 

For this specific problem, `Axon.Loop.run/4` accepts an initial state (in this case the model state). You can think of `Axon.Loop.run/4` kind of look `Enum.reduce/3`:

```elixir
model
|> Axon.Loop.evaluator()
|> Axon.Loop.run(data, trained_model_state, compiler: EXLA)
```

That basically says "run `data` through an evaluation loop with an initial loop state of `trained_model_state`"
